services:
#    bde_user.example:
#        class: BDE\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    bde_user.registration.form.type:
      class: BDE\UserBundle\Form\Type\RegistrationFormType
      arguments: [%fos_user.model.user.class%]
      tags:
          - { name: form.type, alias: bde_user_registration }
