bde_app:
    resource: "@BDEAppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: BDEUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"